services:
  - type: web
    name: cboin-api
    env: docker
    region: frankfurt
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TWITTER_API_KEY
        value: 2QbYBxSKRNuOmwHPEGxGnYQPi
      - key: TWITTER_API_SECRET
        value: aBXZxkUqMDfOlzNBtZIxF2qjmJmYXrxSEv5FIbYlIRCrWVLEEy
      - key: TWITTER_ACCESS_TOKEN
        value: 1747932258453893120-vqknInJajGvrI8EJOUMi5r56WzvzJE
      - key: TWITTER_ACCESS_TOKEN_SECRET
        value: nbI6RWbBqi4N8Rqu51QcDLEgYC9BW8RobfsihujKOBzX6
      - key: TWITTER_BEARER_TOKEN
        value: AAAAAAAAAAAAAAAAAAAAAEyVzAEAAAAAj5QHhp6MNovqjv679NH9u91uMks%3DfBc5q9lW4v6FOQTBAF1El1t6J7hIfZ7MnxH12jdMBOdUPnUcw6
      - key: BINANCE_API_KEY
        value: MSOtGvpGgyN73SUOEyNfmL7fEzWN7tNP7V7HagtHWxUfpSOZavAFksZwBCwZBl7L
      - key: BINANCE_API_SECRET
        value: 45gKGln6PKsp9702zdDrpmPxgLSzQXj1GkwdBrnJ88TTyxWrujugFAffIw97Kpg
      - key: CRYPTOCOMPARE_API_KEY
        value: your_key
      - key: REACT_APP_CRYPTOCOMPARE_API_KEY
        value: your_key
      - key: EMTIA_API_KEY
        value: EeCzp3KmtjxN9I0ZBbLrwIsDQljf24cz
      - key: DATABASE_URL
        value: sqlite:///cboin.db
      - key: DATABASE_PATH
        value: cboin.db
      - key: HTTP_PROXY
        value: http://proxy.example.com:8080
      - key: HTTPS_PROXY
        value: http://proxy.example.com:8080

  - type: worker
    name: cboin-ping-worker
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python ping.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: HTTP_PROXY
        value: http://proxy.example.com:8080
      - key: HTTPS_PROXY
        value: http://proxy.example.com:8080

  - type: web
    name: cboin-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://cboin-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
